#!/bin/bash
source $(dirname "$0")/util.sh


LIBRARY="$1"
PROVISION_TAG="$2"


validateLibName "$LIBRARY" || exit 1
if [ -z "$LIBRARY" ]; then
	exitWithErrMsg "Version was not specified"
fi

if [ -z "$PROVISION_TAG" ]; then
   exitWithErrMsg "PROVISION_TAG for the added binary was not defined."
fi

# SRC_BASE_PATH=`getBasePath "$LIBRARY"` || exit 1
LIB_PATH=`getFullPath "$LIBRARY"` || exit 1
INDYJUMP_TARGET=`getPathForManagedBinary "$LIBRARY" "$PROVISION_TAG"`

echo "Will take library at: $LIB_PATH"
echo "Move it to indyjump directory: $INDYJUMP_TARGET"

if [ ! -f "$LIB_PATH" ]; then
   exitWithErrMsg "File $FILE does not exist."
else 
	cp "$LIB_PATH" "$INDYJUMP_TARGET"
	echo "Proovisioned $LIBRARY with tag $PROVISION_TAG"
fi
