#!/bin/bash
source $(dirname "$0")/util.sh


LIBRARY="$1"
PROVISION_TAG="$2"


validateLibName "$LIBRARY" || exit 1
if [ -z "$LIBRARY" ]; then
	exitWithErrMsg "Version was not specified"
fi

if [ -z "$PROVISION_TAG" ]; then
   exitWithErrMsg "PROVISION_TAG for the added binary was not defined."
fi

# SRC_BASE_PATH=`getBasePath "$LIBRARY"` || exit 1

LIB_PATH=`getFullPath "$LIBRARY"` || exit 1
echo "Will take library at: $LIB_PATH"
if [ ! -f "$LIB_PATH" ]; then
   exitWithErrMsg "File $FILE does not exist."
fi;

INDYJUMP_TARGET=`getPathForManagedBinary "$LIBRARY" "$PROVISION_TAG"`
echo "The binary will be copied to: $INDYJUMP_TARGET"

MANAGED_BINARY_DIR=`dirname "$INDYJUMP_TARGET"`  || exitWithErrMsg "Failed to determine directory where indyjump managed binary will be stored."     
mkdir -p "$MANAGED_BINARY_DIR"

cp "$LIB_PATH" "$INDYJUMP_TARGET"
echo "Proovisioned $LIBRARY with tag '$PROVISION_TAG'"

