#!/bin/bash
source $(dirname "$0")/util.sh

PROVISION_TAG="$1"

if [ -z "$PROVISION_TAG" ]; then
	echo "You have to pass PROVISION_TAG argument which denotes which indy version you want to switch to."
	sh "$(dirname $0)/listindy.sh"
	exit 1
fi;

SETINDY_INDYJUMP_INDY=`getPathForManagedBinary libindy "$PROVISION_TAG"` || exit 1
SETINDY_INDYJUMP_VCX=`getPathForManagedBinary libvcx "$PROVISION_TAG"` || exit 1
SETINDY_INDYJUMP_NULLPAY=`getPathForManagedBinary libnullpay "$PROVISION_TAG"` || exit 1


if [ ! -f "$SETINDY_INDYJUMP_INDY" ]; then
   echo "libindy PROVISION_TAG '$PROVISION_TAG' not found. File '$SETINDY_INDYJUMP_INDY' does not exist."
   MISSING_LIBRARY="yes"
fi

if [ ! -f "$SETINDY_INDYJUMP_VCX" ]; then
   echo "libvcx PROVISION_TAG '$PROVISION_TAG' not found. File '$SETINDY_INDYJUMP_VCX' does not exist."
   MISSING_LIBRARY="yes"
fi

if [ ! -f "$SETINDY_INDYJUMP_NULLPAY" ]; then
   echo "libnullpay PROVISION_TAG '$PROVISION_TAG' not found. File '$SETINDY_INDYJUMP_NULLPAY' does not exist."
   MISSING_LIBRARY="yes"
fi

if [ ! -z "$MISSING_LIBRARY" ]; then
	exitWithErrMsg "One or more libraries for '$PROVISION_TAG' were missing. Won't change the indy version." 
fi;

SIMLINK_INDY=`getSymlinkPath libindy` || exit 1    
SIMLINK_VCX=`getSymlinkPath libvcx` || exit 1    
SIMLINK_NULLPAY=`getSymlinkPath libnullpay` || exit 1    



rm "$SIMLINK_INDY"    2>/dev/null || : 
rm "$SIMLINK_VCX"     2>/dev/null || :
rm "$SIMLINK_NULLPAY" 2>/dev/null || :

# exit
if [ -f $INDY_DYLIB ]; then
	ln -s "$SETINDY_INDYJUMP_INDY" "$SIMLINK_INDY" || exit 1    
	echo "Version of LibIndy changed to $PROVISION_TAG"
fi

if [ -f $INDY_DYLIB ]; then
	ln -s "$SETINDY_INDYJUMP_VCX" "$SIMLINK_VCX" || exit 1    
	echo "Version of LibVCX changed to $PROVISION_TAG"
fi;

if [ -f $INDY_DYLIB ]; then
	ln -s "$SETINDY_INDYJUMP_NULLPAY" "$SIMLINK_NULLPAY" || exit 1    
	echo "Version of LibNullPay changed to $PROVISION_TAG"
fi;