#!/usr/bin/env bash
# INDYJUMPSCRIPT
source $(dirname "$0")/indyjump-utils.sh
if [ "$#" -ne 1 ]; then
    exitWithErrMsg "Illegal number of parameters"
fi

LIBRARY="$1"
validateLibName "$LIBRARY" || exit 1

SRC_BASE_PATH=`getBasePath "$LIBRARY"` || exit 1
validatePathIsCargoProject "$SRC_BASE_PATH" || exit 1

cd "$SRC_BASE_PATH";
echo "Building '$LIBRARY' at $SRC_BASE_PATH/target/debug"
cargo build;
echo "Artefacts at $SRC_BASE_PATH/target/debug"
ls -lah "$SRC_BASE_PATH/target/debug" | grep -i "$LIBRARY"

