#!/usr/bin/env bash
# INDYJUMPSCRIPT
source $(dirname "$0")/indyjump-utils.sh
if [ "$#" -gt 2 ]; then
    exitWithErrMsg "Illegal number of parameters"
fi

LIBRARY="$1"
validateLibName "$LIBRARY" || exit 1

SRC_BASE_PATH=`getBasePath "$LIBRARY"` || exit 1
validatePathIsCargoProject "$SRC_BASE_PATH" || exit 1

BUILD_MODE=${2:-debug}
validateBuildMode "$BUILD_MODE" || exit 1

cd "$SRC_BASE_PATH";

TARGET_PATH=`getFullPath "$LIBRARY" "$BUILD_MODE"` || exit 1
echo "Building '$LIBRARY' in '$BUILD_MODE' mode at path: '$TARGET_PATH'"

case "$BUILD_MODE" in
 debug)
   cargo build;
   ;;
 release)
   cargo build --release;
   ;;
 *)
   exitWithErrMsg "Invalid build mode '$BUILD_MODE'."
   ;;
esac


echo "Build artefact in path: $TARGET_PATH"
ls -lah "$TARGET_PATH" | grep -i "$LIBRARY"

