#!/usr/bin/env bash
source $(dirname "$0")/util.sh

if [ "$1" = "-v" ]; then
    echo -e "You are currently using these indy binaries:\n"
    ls -l `getSysLibsPath` | grep -v ^d | grep indyjump | grep -o -e "->.*"

    echo -e "\nActive indy binaries details:"
    ls -lLh `getSysLibsPath` | grep -v ^d | egrep 'libindy|libnullpay|libvcx'

    echo -e "\nSymlinks:"
    ls -l `getSysLibsPath` | grep -v ^d | grep indyjump
else
    echo -e "You are currently using these indy binaries:\n"
    ls -l `getSysLibsPath` | grep -v ^d | grep indyjump | grep -o -e "->.*"
fi;


