#!/usr/bin/env bash
source $(dirname "$0")/util.sh

PROVISION_TAG="$1"
if [ -z "$PROVISION_TAG" ]; then
	exitWithErrMsg "You have to specify provision tag."
fi

$(dirname "$0")/ijprovision-one "libindy" "$PROVISION_TAG" || exitWithErrMsg "Failed to provision libindy"
$(dirname "$0")/ijprovision-one "libvcx" "$PROVISION_TAG"  || exitWithErrMsg "Failed to provision libvcx"
$(dirname "$0")/ijprovision-one "libnullpay" "$PROVISION_TAG" || exitWithErrMsg "Failed to provision libnullpay"
