#!/usr/bin/env bash
source $(dirname "$0")/util.sh

PROVISION_TAG="$1"
if [ -z "$PROVISION_TAG" ]; then
	exitWithErrMsg "[ij-set-all] Invalid/Misssing script argument PROVISION_TAG"
fi

$(dirname "$0")/ijset-one "libindy" "$PROVISION_TAG" || exitWithErrMsg "Failed to provision libindy"
$(dirname "$0")/ijset-one "libvcx" "$PROVISION_TAG"  || exitWithErrMsg "Failed to provision libvcx"
$(dirname "$0")/ijset-one "libnullpay" "$PROVISION_TAG" || exitWithErrMsg "Failed to provision libnullpay"
