#!/usr/bin/env bash
source $(dirname "$0")/util.sh

LIBRARY="$1"
PROVISION_TAG="$2"

validateLibName "$LIBRARY" || exitWithErrMsg '[ij-set-one] Invalid/Missing script argument LIBRARY.'

if [ -z "$PROVISION_TAG" ]; then
	echo "You have to pass PROVISION_TAG argument which denotes which indy version you want to switch to."
	sh "$(dirname $0)/listindy.sh"
	exit 1
fi;

MANAGED_BINARY=`getPathForManagedBinary "$LIBRARY" "$PROVISION_TAG"` || exitWithErrMsg 'Failed to resolve path for indymjump managed binary.'
if [ ! -f "$MANAGED_BINARY" ]; then
   exitWithErrMsg "$LIBRARY tagged '$PROVISION_TAG' not found. File '$MANAGED_BINARY' does not exist. Won't change the indy version."
fi

SIMLINK_PATH=`getSymlinkPath "$LIBRARY"` || exitWithErrMsg "Failed to resolve symlink path for library '$LIBRARY'"
rm "$SIMLINK_PATH" 2>/dev/null || :

ln -s "$MANAGED_BINARY" "$SIMLINK_PATH" || exitWithErrMsg "Failed to create symlink '$SIMLINK_PATH' ---> '$MANAGED_BINARY'"
echo "Version of '$LIBRARY' changed to '$PROVISION_TAG'"

