#!/usr/bin/env bash
# INDYJUMPSCRIPT

source $(dirname "$0")/indyjump-utils.sh
if [ "$#" -ne 1 ]; then
    exitWithErrMsg "Illegal number of parameters"
fi

PROVISION_TAG="$1"
validateProvisionName "$PROVISION_TAG" || exit 1

$(dirname "$0")/ijump-one "libindy" "$PROVISION_TAG" || errcho "Coudln't change version of libindy to $PROVISION_TAG"
$(dirname "$0")/ijump-one "libvcx" "$PROVISION_TAG"  || errcho "Coudln't change version of libvcx to $PROVISION_TAG"
$(dirname "$0")/ijump-one "libnullpay" "$PROVISION_TAG" || errcho "Coudln't change version of libnullpay to $PROVISION_TAG"
